server:
  port: 8101

spring:
  application:
    name: CollectionService

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  Kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "collection"